Repository LaraAReeves/UNSAM-Frontend, pull requests merged in 2024-12, with the labels that each got.

#11 Tema claro por defecto
  src/App.tsx
  src/main.tsx
Labels: UX, UI

#15 Formulario de registro corregido + features de accesibilidad.
  src/components/pages/register/Register.tsx
  src/routes.tsx
Labels: enhancement, UX, accesibility

#16 Login/tests
  package-lock.json
  package.json
  src/components/pages/login/Login.test.tsx
  src/components/pages/login/Login.tsx
Labels: test

#18 Rutas absolutas reemplazadas por @
  src/App.tsx
  src/components/common/ProtectedRoute.tsx
  src/components/pages/login/Login.test.tsx
  src/components/pages/welcome/Welcome.test.tsx
  src/components/pages/welcome/Welcome.tsx
  src/components/ui/TransparentContainer.tsx
  src/main.tsx
  src/routes.tsx
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: enhancement

#22 Retoque de la vista login
  src/components/pages/login/Login.tsx
Labels: UI

#23 Solución del aspecto de registro
  src/components/pages/register/Register.tsx
Labels: UI

#26 Maquetado perfil de usuario/administrador
  src/components/common/Nav.tsx
  src/components/pages/main/Main.tsx
  src/components/pages/profile/Profile.tsx
  src/components/pages/profile/ProfileButton.tsx
  src/routes.tsx
Labels: UI

#24 Maquetado de ClassRoomCard
  src/components/common/ClassRoomCard.tsx
  src/components/pages/main/map/Map.tsx
Labels: UI

#28 Interfaces para servicios y entidades
  src/data/domain/Entity.ts
  src/data/domain/User.ts
  src/data/service/ServiceInterface.ts
Labels: question, feature

#30 Maquetado de pantalla de búsqueda.
  src/components/common/Nav.tsx
  src/components/common/SearchBar.tsx
  src/components/pages/main/search/Search.tsx
  src/data/mock/ClassData.tsx
  src/routes.tsx
Labels: page, UX, UI

#25 Maquetado Modal
  src/components/common/ClassRoomCard.tsx
  src/components/common/Modal.tsx
  src/components/pages/main/map/Map.tsx
Labels: UI
